In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('cluster-4.csv', sep=';')
df

,Cluster,White,Black or African American,American Indian or Alaskan Native,Asian,Native Hawaiian or other Pacific Islander,Multiple Race,Other Race,TN,FP,FN,TP
0,Euclidean-0,0.481927,0.436945,0.004427,0.030320,0.000419,0.020012,0.025949,498,91,59,165
1,Geodesic-0,0.312484,0.626666,0.004015,0.014152,0.000261,0.015920,0.026502,498,91,59,165
2,Euclidean-1,0.649836,0.065744,0.014612,0.026230,0.000532,0.199834,0.043212,592,32,0,189
3,Geodesic-1,0.683277,0.055374,0.014042,0.024547,0.000536,0.180376,0.041848,592,32,0,189
4,Euclidean-2,0.280133,0.594161,0.004431,0.070510,0.000463,0.014388,0.035914,617,0,62,134
5,Geodesic-2,0.262209,0.628280,0.004597,0.056871,0.000425,0.013910,0.033708,617,0,62,134
6,Euclidean-3,0.230819,0.685531,0.004818,0.033784,0.000219,0.014849,0.029980,488,121,123,81
7,Geodesic-3,0.391436,0.438295,0.008106,0.053748,0.000343,0.074062,0.034010,488,121,123,81